services:
    api1:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api1
        depends_on:
            - db
        expose:
            - "8000"
        cpus: '0.25'
        mem_limit: '0.5GB'
        networks:
            - api-network
        volumes:
            - ./.build/php.ini:/usr/local/etc/php/php.ini

    api2:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api2
        depends_on:
            - db
        expose:
            - "8000"
        cpus: '0.25'
        mem_limit: '0.5GB'
        networks:
            - api-network
        volumes:
            - ./.build/php.ini:/usr/local/etc/php/php.ini

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api1
            - api2
        ports:
            - "9999:9999"
        cpus: '0.25'
        mem_limit: '0.5GB'
        networks:
            - api-network

    db:
        image: mysql
        cpus: '0.75'
        mem_limit: "1.5GB"
        environment:
            - MYSQL_ROOT_PASSWORD=password
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
